### ISSUE TITLE
CRaft 5 > Beta 11 first load issue

### ISSUE THREAD

**Issue by wmdhosting** [verbb/hyper#127]
### Describe the bug

![Snag_afecd1c](https://github.com/verbb/hyper/assets/76176291/ae8f9413-082c-4273-93ac-e1f148503a0b)

### Steps to reproduce

1. Just install and enable multi links

### Craft CMS version

Crfat 5 beta 11

### Plugin version

2.0.0-beta.4

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.4"`.

I'm not keen on adding the 3-dots _and_ the settings slide-out. That's just unnecessary UI. The reason I haven't changed this 3-dots icon like Craft is that represents a menu dropdown. For multi-links, that's true, but for single links, that's only the slide-out if there are multiple tabs in the field layout.

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.5](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.5)

**Comment by wmdhosting** [comment]
By default there are Multiple Tabs..  2 Right
![Snag_b39f016](https://github.com/verbb/hyper/assets/76176291/392defd1-dfc3-4953-8ede-eed496304a19)


Single links  Cog settings works as expected..  thats ok. no need to change anything.. 


But on Multi links  >> when you want to change somethign in Other Tab >> quit unexpected >> and not working as other things in Craft  >>    and every time i need to go to that dropdown and choose setings  >> feels quite odd

**The reason I haven't changed this 3-dots icon like Craft is that represents a menu dropdown**
---------------------------------------------------------------------------

Seems same to me.. 

![Snag_b3d6ae5](https://github.com/verbb/hyper/assets/76176291/7cb645b8-3a22-4b2f-a9ab-0720f3900308)

**Comment by engram-design** [comment]
You're correct that for a multi-link field, the actions best be visually described by 3 dots because it's a dropdown menu. However, this just means an inconsistent icon compared to a single-link field, which would have the settings cog icon.

But having said that and writing that out, they technically describe two different actions, so they _should_ be different icons. I initially was arguing that they should be the same for consistency across single and multi-links, but they do two different things. We're in agreeance.

Updated for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.5"`.

**Comment by wmdhosting** [comment]
Tahnk you very much :)
