### ISSUE TITLE
Make database backups optional on migrations

### ISSUE THREAD

**Issue by jrrdnx** [verbb/hyper#134]
### What are you trying to do?

I'm attempting to run a migration from another existing plugin, in this case Typed Link field. Step 1 Migrate Fields will attempt to automatically run a database backup, but mysqldump is not currently installed/setup properly. Database backups can be performed manually and do not need to be performed during this migration.

### What's your proposed solution?

Include a checkbox to allow this option to be turned off/on when migrating fields.

**Comment by engram-design** [comment]
Take a look at the [`backupOnMigrate`](https://verbb.io/craft-plugins/hyper/docs/get-started/configuration) configuration option for this! It's on by default because it's a really **really** good idea to take a backup of fields and field content beforehand. Particularly as this is run on every environment, including production.

**Comment by jrrdnx** [comment]
Gotcha, thanks. Didn't see a default `config.php` file and hadn't gotten into the docs yet. My bad!
