### ISSUE TITLE
Hyper, when rendering an Entry link, will report status as enabled always

### ISSUE THREAD

**Issue by johnfmorton** [verbb/hyper#154]
### Describe the bug

I have a Hyper field that has been migrated from a LinkIt field. The field accepts both URLs and Entries. On a live entry on the site using a Hyper field, there is a link to a disabled entry. 

In the Twig template, I check to see if the field's Hyper entry is enabled, and it always returns true, regardless of the status of the linked entry, which will cause an empty element to render on the front end.

### Steps to reproduce

1. Create a Hyper field that accepts an Entry.
2. When using the field, link it to another entry.
3. In the Twig template, test the `.enabled` property of the field. 
4. Toggle the linked entries status.
5. Check to see if the Hyper field's enabled property changes.

### Craft CMS version

4.9.2

### Plugin version

1.1.28

### Multi-site?

No

**Comment by engram-design** [comment]
Thanks for the video sent through separately. I can see you're using `entry.hyperField.enabled` which isn't strictly supported, and doesn't reflect the status of a linked-to element. While Link objects for Hyper have a status, that's just because they're faux Elements, and they're always enabled.

I'll look at adding support for the `enabled` state for element fields to bubble-up from the linked-to element to the Link object, much like `title` or `url` does (these properties on a Link object reflect the respective properties on the link-to element, if there is one)

For now, you can get around this be getting the enabled state from the element. `entry.hyperField.element.enabled`, but you'll want to be careful of that as not everything links to an element, so `entry.hyperField.element` may very well be `null` for a URL link type.

**Comment by johnfmorton** [comment]
Thanks for the info. I'll close this issue.
