### ISSUE TITLE
Hyper field CP Error on Craft CMS 4.11+

### ISSUE THREAD

**Issue by leowebguy** [verbb/hyper#183]
### Describe the bug

Hyper field doesn't display Hyper Link Type Dropdown.

craftcms/cms 4.11.1
![Screenshot 2024-08-10 at 5 00 03 PM](https://github.com/user-attachments/assets/497aa966-afec-474e-8c58-581b8e2784ab)

craftcms/cms 4.10.8
![Screenshot 2024-08-10 at 5 04 30 PM](https://github.com/user-attachments/assets/c504c5f6-fe64-4c1f-907f-b5e3c51e1819)

---

console
![Screenshot 2024-08-10 at 5 00 58 PM](https://github.com/user-attachments/assets/6346ef3b-da2f-4415-b6f7-60e871f42f16)

field config
![Screenshot 2024-08-10 at 5 02 03 PM](https://github.com/user-attachments/assets/34b229bd-2981-48db-9c2b-609f8aefbe7d)

### Steps to reproduce

1. upgrade craft to 4.11+

2. hyper field dropdown won't show up

### Craft CMS version

4.11.1

### Plugin version

1.2.1

### Multi-site?

No

### Additional context

When I downgrade craft back to 4.10.8, dropdown show up fine.

**Comment by engram-design** [comment]
This looks pretty similar to the [issue](https://github.com/craftcms/cms/issues/15501) already fixed in fixed in [Hyper 1.2.1](https://github.com/verbb/hyper/releases/tag/1.2.1).

I can't tell if you're using Neo, but that's slightly related and also [fixed](https://github.com/spicywebau/craft-neo/commit/73d46c1dd1d8f103f29d79c24c20c88c28ef0e9c).

But for me on Craft 4.11.1 and Hyper 1.2.1 dropdowns are showing up correctly. 
<img width="429" alt="image" src="https://github.com/user-attachments/assets/0a20bcea-ab23-4f03-a82f-a7e4545fe332">

**Comment by leowebguy** [comment]
hey @engram-design 
this is fresh from today.
Craft 4.11.1 + Hyper 1.2.1

correct, I have Neo 3.9.11

**Comment by engram-design** [comment]
You'll want to update to the latest Neo version to fix this as well - [Neo 4.2.10](https://github.com/spicywebau/craft-neo/releases/tag/4.2.10) which seemed to do the trick for me with the previous JS issues.

**Comment by leowebguy** [comment]
Thank you!
