### ISSUE TITLE
Field Settings - Making changes and saving them, then trying to leave results in an "unsaved changes" message from the browser

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#19]
### Describe the bug

When you change the settings for a Hyper field, save the changes with `cmd+s`, then try to leave the page, you get this:

![image](https://user-images.githubusercontent.com/1250017/221145099-9aab13a6-b085-4192-ba1a-f91b91595b88.png)

### Steps to reproduce

1. Edit a hyper field
2. Hit `cmd+s`
3. Try to leave

### Craft CMS version

4.3.10

### Plugin version

"dev-craft-4 as 1.0.4"

**Comment by engram-design** [comment]
Yep, aware of this one. It's due to the field layout being loaded in for the first link type. It technically _has_ changed because it's an automatic thing, but I'll see what I can do.

**Comment by engram-design** [comment]
I’ll likely address this by not selecting the first link type (assets) automatically when opening the field settings. This is otherwise confusing some people where they don’t realized the field layout is for the asset link type.

But, as soon as you click on a link type, it’ll load the field layout, and there’s not much we can do about that triggering a change.

**Comment by darylknight** [comment]
That makes sense, thanks Josh.

**Comment by engram-design** [comment]
Updated this for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.8"`

**Comment by darylknight** [comment]
Ooo nice! Thank you.

**Comment by engram-design** [comment]
Updated in [1.1.9](https://github.com/verbb/hyper/releases/tag/1.1.9)
