### ISSUE TITLE
Usage with a localized site

### ISSUE THREAD

**Issue by barnslig** [verbb/hyper#45]
### Describe the bug

I want to use the Entry link type on a localized page.

My expected behavior would be that the title and url of the target entry are retrieved for each language in the corresponding language. The selected entry should be the same for all languages.

The actual behavior seems to be that the entry is saved for each language only in the language in which the link field was initially saved. When rendering the link, it links always to the first language's site and not to the current one.

I am not sure whether it is a bug or whether I am configuring the field in a wrong way.

### Steps to reproduce

1. Create a localized setup as described here: [https://craftcms.com/docs/4.x/sites.html#setting-up-a-localized-site](https://craftcms.com/docs/4.x/sites.html#setting-up-a-localized-site)
2. Create a Hyper field with "Translation Method" set to "Translate for each language" and the Entry link type enabled
3. Add the field to a section that is enabled for all languages
4. Select an entry in the field

Now, check the `hyper_element_cache` database table. The colums `title` and `uri` are the same for all languages, instead of being localized.

### Craft CMS version

4.4.3

### Plugin version

1.1.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
The problem is, we can't assume you want to match the site of the picked element with the site of the owner element that you're on. 

For example, I create an entry on Site B, and in my Hyper field, I pick the "About Us" entry also on "Site B". If I switch to the Site A version of that entry we shouldn't assume you want to resolve it to the Site A "About Us" entry. It also assumes that _that_ entry exists for every site - some sections aren't enable for some sites, and you can fine-grainly control when entries even exist on which site. This allows you to pick elements across sites, not just the one you're currently on.

Just to double-check what other link plugins do:

Linkit doesn't actually support linking to an element that's not on the same site as the owner. So even if you pick "About Us - Site B" for a Site B entry, you can't change that to "About Us - Site A". 

Typed Link does allow you to set manage them per-site, but it displays the exact same behaviour Hyper does. The entry element refers to the site you picked originally, not the site-matched one. You can change this on each site entry of course, but the default behaviour is to use the same element/site you picked upon creation.

As your question was specifically about languages, it's still the same concept as managing them per-site.

I'll give this some further thought, but the way around this at the moment is to edit every site (or language) for the entry and pick the corresponding language-specific entry for the Hyper field. This question is really about the initial propagation of Hyper content when you create a new entry.

**Comment by EFWall** [comment]
I would like to chime in here. I have just started testing the plugin and my expectation for how this should work is the same as @barnslig suggests.

I think what we are expecting is that the "entry" link type would function in the same way as the native "Entries" field type in Craft. This is what we are trying to replace and improve upon by using the Hyper plugin.

The "Entries" field type does assume that we want to link to the entry on the current site and that if the entry is not enabled or does not exist on the current site that we do not want to display the entry link at all. This works great for those of us managing sites that are localized in multiple languages or versions.

Perhaps just add a config setting to the entry link type to allow the admin user to set which way they prefer the entry link to function. They could choose to have it function like a relation (native Craft method, as we are describing here) or as a direct link (as it currently functions).

**Comment by roelvanhintum** [comment]
@engram-design, is there any progress on this? I have to side with @EFWall on the expectation of an entry field like functionality. It seems logical for all other link types and "link text" to let it behave as is. Maybe more fine grained control on which parts should be translated, would be a solution.

**Comment by engram-design** [comment]
I've just spent some time working on this, and have tried to replicate the expected behaviour with element fields. Hyper is slightly different in that we allow you to target the site _and_ element, unlike element select fields. It'd be nice when Craft decides to implement saving the `siteId` and `elementId` for an element field.

So, what will happen now is that when a new link is created (single or multi) the chosen element for the link block will be propagated to the same block on other sites, changing to reference that same element you've picked, but for that respective site.

This only does this for new link blocks, because you need to be able to edit the linked-to element and not have it just automatically always be the respective site's element. There are times you actually want the linked-to element for another site's link to be empty, so we can't do empty checks.

Hope that makes sense in practice!

Updated for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.25"`

**Comment by roelvanhintum** [comment]
Thanks for the fast response @engram-design! We did some tests and this seems to work exactly as expected.

**Comment by engram-design** [comment]
Updated in [1.1.27](https://github.com/verbb/hyper/releases/tag/1.1.27)
