### ISSUE TITLE
Possibility to purge caches (possible bug?)

### ISSUE THREAD

**Issue by Antimated** [verbb/hyper#54]
### What are you trying to do?

Heya 👋

I'm currently building a website which allows you to select categories from a hyper field. The category have a custom built url built like so:

`{{craft.entries().section('pages').type('productList').siteId(siteId).one().slug}}?categories=assortment={id}`

The issue is that I changed the url to be like this:

`{{craft.entries().section('pages').type('productList').siteId(siteId).one().slug}}?categories=productAssortment={id}`

The problem is that the url doesn't seem to update and I'm not able to purge the cache for the hyper fields I'm using :(

### What's your proposed solution?

A possibility to purge the hyper field caches so URI's  are actually updated if you change the URI of a category, ...
Preferably by clearing some kind of cache on the **Utilities -> Caches** page.

### Additional context

The affected hyper field is inside a matrix block. The hyper field is set up as a multiple field.

**Comment by engram-design** [comment]
So that code sample is how you have the URL settings for the category group? But yes, that's probably a good point, and I'll think on how best to handle that in a smart way.

But, for now, those caches for an element like this are stored in the `hyper_element_cache` table. You're absolutely free to delete everything in this table. It'll re-generate itself whenever the link is loaded next.

**Comment by Antimated** [comment]
> So that code sample is how you have the URL settings for the category group?

Yes that's right! Seemed to only be an issue with querystrings.

**Comment by engram-design** [comment]
Added for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.8"`

**Comment by engram-design** [comment]
Added in [1.1.9](https://github.com/verbb/hyper/releases/tag/1.1.9)
