### ISSUE TITLE
Ability to use `getLinkAttributes()` to pull in the href, classes, new window, etc details

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/hyper#6]
### What are you trying to do?

Coming from Typed Link Field I've really enjoyed leveraging the `{{ field.getLinkAttributes() }}` function so I can construct anchor tags that need to include iconography:

```twig
<a {{ cta.getLinkAttributes() }} class="flex items-center gap-1">
  {{ cta.getText() }}
  {{ svg('@images/arrow.svg') | attr({ class: 'w-5 h-5' }) }}
</a>
```

That allows me to easily pull in all the `href`, `target`, `rel`, etc stuff that is being constructed behind-the-scenes.

### What's your proposed solution?

Having a Hyper equivalent would be excellent—though if there's a simpler way to include custom HTML _within_ the generated link using `getLink()` I'd be open to that, too.

**Comment by Mosnar** [comment]
Yes please! This would make the migration painless for us as well.

**Comment by engram-design** [comment]
That same function exists! [`getLinkAttributes()`](https://verbb.io/craft-plugins/hyper/docs/developers/link#methods-1) although it returns an array instead of a string for ultimate flexibility. This allows you to modify the content of it after the fact, for whatever reason.

In addition, you could simplify that by providing any extra attributes:

```twig
<a {{ attr(cta.getLinkAttributes({ class: 'flex items-center gap-1' })) }}>
  {{ cta.getText() }}
  {{ svg('@images/arrow.svg') | attr({ class: 'w-5 h-5' }) }}
</a>
```

Or even use Craft's `tag` functions for a slightly cleaner markup.

```twig
{% set text %}
    {{ cta.getText() }}
    {{ svg('@images/arrow.svg') | attr({ class: 'w-5 h-5' }) }}
{% endset %}

{{ tag('a', cta.getLinkAttributes({
    class: 'flex items-center gap-1',
    text: text,
})) }}
```

Would maybe a `asString` param to the function help with migration?

**Comment by engram-design** [comment]
FYI, added the `asString` param in [1.0.2](https://github.com/verbb/hyper/releases/tag/1.0.2) so you can migrate _hopefully_ pretty painlessly.

```diff
- <a {{ cta.getLinkAttributes() }} class="flex items-center gap-1">
+ <a {{ cta.getLinkAttributes([], true) }} class="flex items-center gap-1">
  {{ cta.getText() }}
  {{ svg('@images/arrow.svg') | attr({ class: 'w-5 h-5' }) }}
</a>
```

**Comment by aaronbushnell** [comment]
This is great, thanks so much!
