### ISSUE TITLE
Link is not saved in NEO field when we use it in child blocks

### ISSUE THREAD

**Issue by nielcapp1** [verbb/hyper#90]
### Describe the bug

When I try to save a link in a neo-field where the block with the hyper field is assigned as a child block to a neo block, my link is not saved. 

This bug also occurs if we specify the setting in the neo block with the hyperfield that the relevant block at the top should not be used.

### Steps to reproduce

1. Create a Craft CMS project with Neo (3.9.0) and Hyper (1.1.12)
2. Create a Neo field
3. Create the Longform block with the child blocks:

![Scherm­afbeelding 2023-09-21 om 11 06 25](https://github.com/verbb/hyper/assets/22441671/d4202134-2e8c-4d7d-8e68-fc9b5c315b24)

4. The settings of the Longform block in Neo:

![Scherm­afbeelding 2023-09-21 om 11 07 03](https://github.com/verbb/hyper/assets/22441671/4bcfecd4-a36e-485c-b35e-155f434cae50)

5. The settings of the Actions block in longform:

![Scherm­afbeelding 2023-09-21 om 11 07 03](https://github.com/verbb/hyper/assets/22441671/ece9ab99-d7ab-442a-a252-c7f3c72a66f3)

6. The field layout of the Actions block:

![Scherm­afbeelding 2023-09-21 om 11 11 12](https://github.com/verbb/hyper/assets/22441671/bc416a0a-bcd3-497e-81ee-8a9344e189cb)

7. The settings of the Actions field:

![Scherm­afbeelding 2023-09-21 om 11 11 53](https://github.com/verbb/hyper/assets/22441671/3f6b75d0-eb99-4018-add4-f8f03c32e8ad)

8. Add the Neo field to a single and try to save some content as described in the bug.

### Craft CMS version

4.5.5

### Plugin version

1.1.12

### Multi-site?

No

### Additional context

The version of Neo was 3.9.0. After downgrading NEO to 3.8.6 I no longer have this problem.

**Comment by engram-design** [comment]
Seems to be working for me, although can you confirm your `5. The settings of the Actions block in longform:` setting, which is repeated from the Longform block settings?

**Comment by nielcapp1** [comment]
Yes, in the Longform block we can repeat the Title, Text and Actions blocks.

**Comment by engram-design** [comment]
What I mean is - they’re the exact same image. Is this correct? I’m pretty sure I understand your setup but I wanted to double check as I can’t replicate this behavior.

when you mention is doesn’t save, do _any_ values stay? Do you see the auto save spinner near the entry title as you edit the Neo and Hyper field?

**Comment by stevendierick** [comment]
I'm having the same issues. But I'm starting to suspect this is a Neo thing... Doesn't seem to work for other fields either, such as plain text and asset fields. Vizy also seems to fail to initialize within Neo.

**1. Hyper in Neo tests**
- Video: https://share.cleanshot.com/2sd7Wch6cLkzCFx4VnnY
- Parent block settings: https://share.cleanshot.com/NJgTF5F7XpKy08fcNkDT
- Child block settings: https://share.cleanshot.com/F2yQ3pkFCyTJY2WMFDXl

**2. Plain text, asset, Vizy, and Hyper in Neo tests**
- https://share.cleanshot.com/6pyBfWq50BHKrBQFnv5l

Running all the latest versions:

- Craft CMS version: 4.5.5
- Hyper version: 1.1.12
- Vizy version: 2.1.9
- Neo version: 3.9.1

I'll open an issue at Neo later today and reference this issue.

**Edit:** Opened an issue at Neo - https://github.com/spicywebau/craft-neo/issues/787

**Comment by ttempleton** [comment]
Confirming this was a Neo bug related to changes in 3.9, fixed now in 3.9.2.

**Comment by stevendierick** [comment]
Hyper still seems to have some issues with the new Neo updates.

When you add a block with a Hyper field, the field isn't fully initialised the first time. Refreshing or saving fixes this BUT it will break nested Hyper fields (via slideout).

Nested Hyper fields (via slideout) only work if you save again after the initial save (to fix the initialization), and only after each save when adding a new parent link. If you add a new parent link without saving first then adding nested Hyper links will also fail.

Also, when adding nested Hyper links (via slideout) and re-opening it without saving the entry, it won't show your nested Hyper links anymore. BUT if you cancel the slideout and then save the entry, the nested Hyper links will have been added. BUT if you would have saved the slideout, with the empty nester Hyper links, and continue to save your page then the nested Hyper links will have been removed (or still empty).

I've also tested nested Hyper fields directly in the parent field (not via slideout) and that seems to work fine. I remember that nested Hyper links via slideout has different behaviour from my [original nesting issue](https://github.com/verbb/hyper/issues/66). Might be related since the new Neo changes?

I've recorded a couple of tests:

- https://share.cleanshot.com/YYn7VsnSGzlZb1TPT2FD
- https://share.cleanshot.com/BRcRtxm6tJwKr1TNwMQJ

Versions:

- Craft CMS: 4.5.5
- Hyper: 1.1.12
- Neo: 3.9.2

**Comment by engram-design** [comment]
I'm not sure of the details of what's happened with Neo, but it now no longer loads the `hyper.js` file, despite loading the inline `new Craft.Hyper.Input()` call - we need both.

It could be down to how we register the JS script with Vite, but it's an asset bundle, so that should be pretty standard.

**Comment by ttempleton** [comment]
The change in Neo causing that is the same as described in https://github.com/verbb/vizy/issues/260#issuecomment-1736518993. In this case it means that the registered `hyper.js` file isn't being picked up. I'm honestly not sure how that would need to be fixed (e.g. adding the Craft view's `startJsFileBuffer()` / `clearJsFileBuffer()` methods to Neo isn't picking up anything). But in the meantime, I've just released Neo 3.9.3 with the `enableLazyLoadingNewBlocks` plugin setting, which can be disabled in the `config/neo.php` file to restore pre-3.9.0 behaviour and work around this issue.

**Comment by engram-design** [comment]
@ttempleton Thanks for that. Yep, I went for a deep-dive into what's going on as `startJsFileBuffer()` doesn't do anything. Initially I thought [this change](https://github.com/craftcms/cms/commit/7510a39c99aef04e86d09e19bb91a1bb53a4db26) might be the culprit, but reverting that had no effect. Looking into it.

**Comment by ttempleton** [comment]
This is fixed in Neo 3.9.4, read from here on for details: https://github.com/spicywebau/craft-neo/issues/790#issuecomment-1737316726
