### ISSUE TITLE
Config to output Relative URL, instead of Absolute URL for Entry type links

### ISSUE THREAD

**Issue by leowebguy** [verbb/hyper#92]
### What are you trying to do?

When creating a link type Entry and selecting that entry

![Screenshot 2023-09-22 at 8 03 10 AM](https://github.com/verbb/hyper/assets/8460020/dffabfa4-a50d-48e5-b7c6-50f0938a9949)

... the output is 

`<a class="btn btn-primary" href="https://mywebsite.com/my-page">Click here</a>`

... ideally the link should be 

`<a class="btn btn-primary" href="/my-page">Click here</a>`

### What's your proposed solution?

Have an option to return something like `'/' ~ craft.entries.id(vars.linkValue).one().uri` or similar via config.

Reasons to use relative url: https://www.tutorialspoint.com/difference-between-an-absolute-url-and-a-relative-url

**Comment by engram-design** [comment]
I don't really agree with the premise here, sorry. The URL is controlled by the entry element in this case, so it's the same as if we were to call `{{ entry.url }}` in our templates, that doesn't render the relative URL. I'm open to adding it as an option for users who _really_ want this, but I think it'll just introduce complexity. We're essentially undoing what `entry.url` does, or relying on `entry.uri`.

My biggest concern is that there's a difference in behaviour for Assets (and maybe other elements). `{{ asset.url }}` returns the full absolute path, but `{{ asset.uri }}` returns nothing. So this behaviour would be specific to entries.

Another thing to consider - what about when I want to link to an entry that's not on the same site as the current one? If it's always relative, you assume that you're always linking to the same site.

As for the article referenced:
- Quicker Coding: Debatable, and not an issue for Craft or Hyper in this context.
- Staging Environment: Not really an issue with Craft, as unlike Wordpress, the Site URL is controlled (usually) through an `.env` variable.
- Quicker Load Times: I've never heard of this anywhere, and interested to see some data to back this up. From what I've read it's simply due to the smaller character count, which is a bit of a stretch to call that a performance factor.
